### PR TITLE
Add social auth for account sign in

### PR DESCRIPTION
**Pull request by cabarnes**
Add buttons to use `GitHub` and `Google` for authentication. This won't "just work" as we'll need to register applications in the `rovercode` `Google` and `GitHub` organizations. Then, use the Django admin to enter the credentials in the deployed application. `Twitter` and `Facebook` can be added fairly easily as well.

image

### CODE REVIEW

**Comment by aninternetof** [comment]
This is a really cool idea.

I'm going to pull it down and check it out. I assume the "sign up" page is similar?

**Comment by aninternetof** [comment]
image
This might be expected based on what still needs to be done after it runs. Is this what you see before you create the credentials for Google and Github?

**Comment by cabarnes** [comment]
Right, the applications need to be added in Django admin (`/admin/socialaccount/socialapp/`)

**Comment by aninternetof** [comment]
When you run with `-f dev.yaml`, do you see things about installing the rds CA certificate? I'm surpised to see that stuff, since it seems to only be in the production Dockerfile. I'm sure it was either always happening or related to the last PR.

**Comment by cabarnes** [comment]
Have you done a `docker-compose -f dev.yml build django`? You might have a previous production build that is running.

**Comment by aninternetof** [comment]
Huh, that must have been it.  I'll write up a ticket if I reproduce it ever.

**Comment by aninternetof** [comment]
I'm trying to imagine the flow since there's no "Sign up with Google" button.

1. User creates rovercode account with username and password
2. User later signs in using Google. Google credentials get associated with rovercode account.
3. User can sign in with Google anytime.

Does that sound right?

**Comment by cabarnes** [comment]
We would want them to sign in with the social account first. It creates the rovercode account for them after authenticating. I'm thinking we might want to just remove the `Sign Up` button from the nav bar since there is a link to it in the `Sign In` page. It's something they would only do once ever and if they click to get in via social account then they never have to.

**Comment by aninternetof** [comment]
Got it. That makes more sense. I've seen other apps gracefully handle my logging in w/ Google after having already created a regular account by noticing that the email was the same and asking if I wanted to associate them. We'll see what Django does in that scenario. But I'm ok having that as not an officially supported flow; if they end up with two separate accounts, it's their own fault.

That also addresses my other concern: A long time ago I changed the change User model to make email optional. I was concerned if that could mess things up with associating account;  but, if it never attempts to associate them, there's no problem.

**Comment by aninternetof** [comment]
Have you created a superuser for yourself on beta.rovercode.com? Or would you like me to try adding the credentials? I'm good either way.

**Comment by cabarnes** [comment]
Ok, I'll go ahead and remove `Sign Up` from the nav bar in this PR.

**Comment by cabarnes** [comment]
We need to create the applications in Google and GitHub that are owned by the `rovercode` organization. I think you have the credentials to do that so you're probably the best one to add the applications in the Django admin once those are created.

**Comment by aninternetof** [comment]
Ok, cool, it should be no problem. I'm not sure we have a Google account owned by rovercode, but I could create one.

**Comment by aninternetof** [comment]
How would you feel about changing the ordering of the options, since it's now also the starting point for people signing up. Maybe:

1. Don't have an account yet? [Create an account here](https://rovercode.com/accounts/signup/).
2. Or, sign up / sign in with your existing third party account. (Github and Google buttons)
3. Or sign in with your rovercode credentials. (form)

**Comment by aninternetof** [comment]
Last thought: maybe the remaining nav bar button should say `Sign Up / Sign In`? I imagine most people would know to click `Sign In` even if they haven't made an account yet, but it could be better to be explicit?

**Comment by cabarnes** [comment]
The wording is fine but I still like having the social logins first. Otherwise, I feel like people would always go to the sign up page and not use it. Changing the nav bar to `sign up/sign in` is fine with me if you think that would help people.

**Comment by aninternetof** [comment]
Sounds good -- let's leave them at the top. How about this?

-----------


You can sign up / sign in with one of your existing third-party accounts.
[Github button] [Google button]

Don't have any of those accounts? [Create a rovercode account](https//:asdf.com).

Already have a rovercode account? Sign in here:
[form box]
[form box]
[sign in button]
forgot your password?

**Comment by cabarnes** [comment]
I like that. I think it'll be easier to understand. I'll make the change.

**Comment by cabarnes** [comment]
New look:
image

**Comment by aninternetof** [comment]
Looks great! I'll try adding the google/github app credentials later tonight!

**Pull request merged**
