### PR TITLE
Show guide attribute

### PR DESCRIPTION
**Pull request by cabarnes**
* Add `show_guide` attribute to a user
* Add API to modify `show_guide`
* Add `show_guide` to JWT so no additional API call is required to determine whether to show the guide
* Removed lots of unused code

### CODE REVIEW

**Comment by aninternetof** [comment]
> Add show_guide to JWT so no additional API call is required to determine whether to show the guide

Wow, nice.

**Comment by aninternetof** [comment]
Trying to register a new user, I'm getting this error:

```
django_1           |     raise NoReverseMatch("%s is not a registered namespace" % key)
django_1           | django.urls.exceptions.NoReverseMatch: 'users' is not a registered namespace
django_1           | [06/Jun/2020 02:55:26] "POST /jwt/auth/registration/ HTTP/1.1" 500 20362
```

Could be something weird on my local setup. I'm going to keep investigating.

**Comment by aninternetof** [comment]
^ (trying to create a new user using the UI, on the branch from this PR https://github.com/rovercode/rovercode-ui/pull/214)

**Comment by cabarnes** [comment]
Might be that I got rid of too much. I didn't realize that the jwt auth used the users api

**Comment by cabarnes** [comment]
@aninternetof Creating a user should work now

**Pull request merged**
