### PR TITLE
Authentication Cleanup

### PR DESCRIPTION
**Pull request by cabarnes**
* Transitions the backend to only allow token-based authentication.
* Removes the blog and mission control routes since they are no longer needed and wouldn't work with token-based authentication.
* Removes [AuthenticationMiddleware](https://docs.djangoproject.com/en/2.1/ref/middleware/#django.contrib.auth.middleware.AuthenticationMiddleware) which caused an issue requiring clearing cookies before a social auth user could authenticate again

### CODE REVIEW

**Comment by cabarnes** [comment]
Token auth worked locally for me on the API docs. Did you use `JWT` for the `Scheme`?

**Comment by aninternetof** [comment]
I did! Must have been doing something wrong.

Since you've proven it works, then there's no issue.

**Comment by cabarnes** [comment]
Maybe I'm seeing the same thing that you saw. When I go to `alpha` and do token authentication, none of the private routes are available. Probably when I was doing it locally I had some kind of session open. I'll look at how to configure that to show those routes when token authentication is used.

**Comment by aninternetof** [comment]
Cool!

**Comment by cabarnes** [comment]
@aninternetof This should list all of the routes now in the API documentation. It works with token authentication for me. Can you give it a try?

**Comment by aninternetof** [comment]
Trying it out!

**Comment by aninternetof** [comment]
Works great now! Good find on that `public` flag.

**Pull request merged**
