### PR TITLE
Break out and version the API

### LINKED ISSUE #100: Version the API
The API needs to be versioned and broken out to make creating clients and documenting easier.

### PR DESCRIPTION
**Pull request by cabarnes**
Closes #100 

Relevant URLs:
```
/api/api-auth/login/	django.contrib.auth.views.login	api:rest_framework:login	
/api/api-auth/logout/	django.contrib.auth.views.logout	api:rest_framework:logout	
/api/v1/	rest_framework.routers.APIRootView	api:v1:api-root	
/api/v1/.<format>/	rest_framework.routers.APIRootView	api:v1:api-root	
/api/v1/block-diagrams.<format>/	api.views.BlockDiagramViewSet	api:v1:blockdiagram-list	
/api/v1/block-diagrams/	api.views.BlockDiagramViewSet	api:v1:blockdiagram-list	
/api/v1/block-diagrams/<pk>.<format>/	api.views.BlockDiagramViewSet	api:v1:blockdiagram-detail	
/api/v1/block-diagrams/<pk>/	api.views.BlockDiagramViewSet	api:v1:blockdiagram-detail	
/api/v1/rovers.<format>/	api.views.RoverViewSet	api:v1:rover-list	
/api/v1/rovers/	api.views.RoverViewSet	api:v1:rover-list	
/api/v1/rovers/<pk>.<format>/	api.views.RoverViewSet	api:v1:rover-detail	
/api/v1/rovers/<pk>/	api.views.RoverViewSet	api:v1:rover-detail	
/mission-control/	mission_control.views.home	mission-control:home	
/mission-control/bd-list/	mission_control.views.bd_list	mission-control:bd_list	
/mission-control/load/<bd>/	mission_control.views.home	mission-control:home_with_load	
/mission-control/rover-list/	mission_control.views.rover_list	mission-control:rover_list	
/mission-control/rover-settings/<pk>/	mission_control.views.rover_settings	mission-control:rover_settings
```

### CODE REVIEW

**Comment by aninternetof** [comment]
General question: why do the last 4 urls in your list remain outside of `/api/v1` ?

**Comment by cabarnes** [comment]
@aninternetof Because they aren't APIs. They are HTML pages.

**Comment by aninternetof** [comment]
@cabarnes, oh right! Thanks!

**Comment by cabarnes** [comment]
@aninternetof I fixed the rest framework authentication. It can't be in a nested namespace. You can now log in and out of the browsable API. These are now the URLs:
```
/api-auth/login/	django.contrib.auth.views.login	rest_framework:login	
/api-auth/logout/	django.contrib.auth.views.logout	rest_framework:logout	
/api/v1/	rest_framework.routers.APIRootView	api:v1:api-root	
/api/v1/.<format>/	rest_framework.routers.APIRootView	api:v1:api-root	
/api/v1/block-diagrams.<format>/	api.views.BlockDiagramViewSet	api:v1:blockdiagram-list	
/api/v1/block-diagrams/	api.views.BlockDiagramViewSet	api:v1:blockdiagram-list	
/api/v1/block-diagrams/<pk>.<format>/	api.views.BlockDiagramViewSet	api:v1:blockdiagram-detail	
/api/v1/block-diagrams/<pk>/	api.views.BlockDiagramViewSet	api:v1:blockdiagram-detail	
/api/v1/rovers.<format>/	api.views.RoverViewSet	api:v1:rover-list	
/api/v1/rovers/	api.views.RoverViewSet	api:v1:rover-list	
/api/v1/rovers/<pk>.<format>/	api.views.RoverViewSet	api:v1:rover-detail	
/api/v1/rovers/<pk>/	api.views.RoverViewSet	api:v1:rover-detail	
```

**Comment by aninternetof** [comment]
Hey, now that's cool. DRF provides its own login page!

**Pull request merged**
