### PR TITLE
Provide 'next_url' to social login

### PR DESCRIPTION
**Pull request by cabarnes**
Stores the `next` parameter in the session. Provides the value to the frontend in the callback response after the login has succeeded.

### CODE REVIEW

**Comment by aninternetof** [comment]
This is really clean and slick!
If we use the session, I think we will need to tell Django to start using some kind of distributed session memory (redis) again, right? Using only local memory for the session, another instance in the cluster might handle the callback and not know anything about a next parameter stored in the session on a different instance.

**Comment by aninternetof** [comment]
It's possible we could turn on some stickiness in the load balancer. Though I don't think that would help here, since the first request is coming from the UI, and the second request is coming from Google/Github.

**Comment by cabarnes** [comment]
@aninternetof It's actually using the database currently: https://docs.djangoproject.com/en/3.1/topics/http/sessions/#configuring-the-session-engine. I figured this was not going to be much more load on the database than any other queries going on for programs/courses/etc

**Comment by aninternetof** [comment]
Ha, awesome! I had no idea that was an option. And yes, I agree, that's not too much extra load on the database.

**Review by aninternetof — APPROVED** [review]
Very nice.

**Pull request merged**
